apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-kube-controller-manager-operator
  name: kube-controller-manager-operator
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
