apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-kube-controller-manager-operator
  name: kube-controller-manager-operator-config
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
data:
  config.yaml: |
    apiVersion: operator.openshift.io/v1
    kind: GenericOperatorConfig
